apiVersion: v1
kind: Service
metadata:
  name: django-api-service
  namespace: starter
spec:
  selector:
    app: django-api
    tier: backend
  ports:
    - port: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
  namespace: starter
  labels:
    app: django-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django-api
        tier: backend
    spec:
      containers:
      - name: django-api
        image: angular-django-starter-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: django-api